package com.agile.engine.cuffaro.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

import com.agile.engine.cuffaro.enums.TransactionTypeEnum;
import com.agile.engine.cuffaro.model.TransactionItem;

public class TransactionDTO implements Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -7929394647140356419L;

	/**
	 * Unique transaction identifier, generated by the service, when the transaction is being stored.
	 */
	private String transactionId;
	
	private TransactionTypeEnum transactionType;
	
	/**
	 * Transaction numeric value. Incrementing or decrementing the account balance, based on the transaction type.
	 */
	private Double amount;
	
	/**
	 * Effective date-time, generated by the service, when the transaction is being stored. 
	 */
	private Date effectiveDate;

	public TransactionDTO(String transactionId, TransactionTypeEnum transactionType, Double amount,
			Date effectiveDate) {
		super();
		this.transactionId = transactionId;
		this.transactionType = transactionType;
		this.amount = amount;
		this.effectiveDate = effectiveDate;
	}
	
	public TransactionDTO(TransactionItem item) {
		this(item.getTransactionId(), item.getTransactionType(), item.getAmount(), item.getEffectiveDate());
	}

	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public TransactionTypeEnum getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(TransactionTypeEnum transactionType) {
		this.transactionType = transactionType;
	}

	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Date getEffectiveDate() {
		return effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}


	public String toJson() {
		return "{\n" + 
				"        \"transactionId\": \""+transactionId + "\",\r\n" + 
				"        \"transactionType\": \"" + transactionType + "\",\r\n" + 
				"        \"amount\": " + amount + ",\r\n" + 
				"        \"effectiveDate\": \""+effectiveDate+"\"\r\n" + 
				"    }";
				
	}
}
